apiVersion: theia.cloud/v1beta8
kind: Session
metadata:
  creationTimestamp: "2026-01-02T09:08:37Z"
  generation: 1
  labels:
    app.henkan.io/henkanProjectName: busra
    app.henkan.io/workspaceName: bartu-test
    app.henkan.io/workspaceUser: bartu
  name: bartu-bartu-test
  namespace: henkan-designer
  resourceVersion: "88801740"
  uid: 425f4989-2f8d-4cb5-ab09-52a6358b623c
spec:
  appDefinition: henkan-designer
  envVars:
    COMMIT_GENAI_ENDPOINT: https://henkan-genai.172.12.2.32.sslip.io/webhook/6e201b9b-ca39-44d8-9600-70520911ea5c
    EMAIL: bartu@globalmaksimum.com
    GIT_AUTHOR_NAME: bartu
    GIT_SSL_NO_VERIFY: "true"
    HENKAN_GIT_EMAIL: bartu@globalmaksimum.com
    HENKAN_GIT_USER: bartu
    HENKAN_META_API_URL: http://henkan-metaapi.henkan-metaapi
    HENKAN_PROJECT_GIT_URL: https://github.com/GlobalMaksimum/henkan-etl-flow-project.git
    HENKAN_PROJECT_NAME: busra
  name: bartu-bartu-test
  sessionSecret: henkansecret
  user: bartu
  workspace: bartu-bartu-test
status:
  lastActivity: 1767344918892
  operatorStatus: HANDLED
  url: designer.172.12.2.32.sslip.io/425f4989-2f8d-4cb5-ab09-52a6358b623c/
