apiVersion: example.suleyman.io/v1
kind: Session
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.suleyman.io/v1","kind":"Session","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"sample-app","envVars":{"COMMIT_GENAI_ENDPOINT":"https://example.com/webhook/xyz","EMAIL":"bartu@globalmaksimum.com","GIT_AUTHOR_NAME":"bartu","GIT_SSL_NO_VERIFY":"true","HENKAN_GIT_EMAIL":"bartu@globalmaksimum.com","HENKAN_GIT_USER":"bartu","HENKAN_META_API_URL":"http://henkan-metaapi.henkan-metaapi","HENKAN_PROJECT_GIT_URL":"https://github.com/GlobalMaksimum/henkan-etl-flow-project.git","HENKAN_PROJECT_NAME":"busra"},"name":"bartu-demo-ws","sessionSecret":"henkansecret","user":"bartu","workspace":"bartu-demo-ws"}}
  creationTimestamp: "2026-01-02T11:18:36Z"
  finalizers:
  - sessions.example.suleyman.io/finalizer
  generation: 1
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
  - apiVersion: example.suleyman.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Workspace
    name: bartu-demo-ws
    uid: d3ccdcce-2874-4e42-9e49-b4bc934aa992
  resourceVersion: "105510"
  uid: 96aff083-e1a9-4a76-b51f-43cf67a945e3
spec:
  appDefinition: sample-app
  envVars:
    COMMIT_GENAI_ENDPOINT: https://example.com/webhook/xyz
    EMAIL: bartu@globalmaksimum.com
    GIT_AUTHOR_NAME: bartu
    GIT_SSL_NO_VERIFY: "true"
    HENKAN_GIT_EMAIL: bartu@globalmaksimum.com
    HENKAN_GIT_USER: bartu
    HENKAN_META_API_URL: http://henkan-metaapi.henkan-metaapi
    HENKAN_PROJECT_GIT_URL: https://github.com/GlobalMaksimum/henkan-etl-flow-project.git
    HENKAN_PROJECT_NAME: busra
  name: bartu-demo-ws
  sessionSecret: henkansecret
  user: bartu
  workspace: bartu-demo-ws
status:
  lastActivity: 1767352716798
  operatorMessage: Session is running
  operatorStatus: HANDLED
  url: theia.localtest.me/96aff083-e1a9-4a76-b51f-43cf67a945e3/
